### ISSUE TITLE
Feature request: Search bar

### ISSUE THREAD

**Issue by ftocco** [CodeInKlingon/vscode-git-worktree#13]
Hi, first of all thanks for this simple and effective extension, it has been a pleasure to work with.

Would it be possible in any way to have a simple search bar on top that restricts the number of shown worktrees to the ones matching the substring? It would make navigating large amount of worktrees much quicker.

Thanks again for the time you are saving me daily!

**Comment by CodeInKlingon** [comment]
Probably not possible to add that due to how the tree views work but vscode has a built in feature for searching like this already using a keyboard shortcut!
Try pressing ctl + alt + f or command + option + f which will open a floating search box. 
<img width="348" alt="Screenshot 2024-05-27 at 1 42 39 PM" src="https://github.com/CodeInKlingon/vscode-git-worktree/assets/9805593/685b3da3-31c1-4471-9b90-ebcee735bcb8">

**Comment by ftocco** [comment]
Oh that's very handy, pretty much satisfies my necessities, thanks a lot for the assistance!

**Comment by CodeInKlingon** [comment]
No problem at all! Thank you for your input and for using the extension! I didn't realize vscode had that search feature until you brought it up and I started looking into it. I should definitely document that in the readme.
